name: CI for nRF Connect SDK on nRF52840

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git \
            cmake \
            ninja-build \
            gperf \
            ccache \
            dfu-util \
            device-tree-compiler \
            wget \
            python3-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            xz-utils \
            file \
            make \
            gcc-multilib \
            g++-multilib \
            libsdl2-dev

      - name: Install nRF Connect SDK and Toolchain
        run: |
          # Download and install nRF Connect SDK v2.6.1
          wget https://github.com/nrfconnect/sdk-nrf/archive/refs/tags/v2.6.1.zip
          unzip v2.6.1.zip
          mv sdk-nrf-2.6.1 nrfconnect-sdk
          
          # Install the toolchain via the official toolchain manager script
          wget https://nordicsemi.github.io/pc-nrfconnect-toolchain-manager/ToolchainManagerLinux.tar.gz
          tar -xzf ToolchainManagerLinux.tar.gz
          ./toolchain-manager --version
          
          # Use Toolchain Manager to install the correct version of the toolchain
          ./toolchain-manager install 2.6.1
          source ~/ncs/toolchain/v2.6.1/zephyr/zephyr-env.sh
          
      - name: Set up Zephyr environment (West and others)
        run: |
          pip3 install west
          west init -l nrfconnect-sdk
          west update
          west zephyr-export
          
      - name: Build the application for nRF52840
        run: |
          west build -b nrf52840dk_nrf52840

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: build/zephyr/*.hex
name: CI for nRF Connect SDK on nRF52840

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            git \
            cmake \
            ninja-build \
            gperf \
            ccache \
            dfu-util \
            device-tree-compiler \
            wget \
            python3-dev \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            xz-utils \
            file \
            make \
            gcc-multilib \
            g++-multilib \
            libsdl2-dev

      - name: Install nRF Connect SDK and Toolchain
        run: |
          # Download and install nRF Connect SDK v2.6.1
          wget https://github.com/nrfconnect/sdk-nrf/archive/refs/tags/v2.6.1.zip
          unzip v2.6.1.zip
          mv sdk-nrf-2.6.1 nrfconnect-sdk
          
          # Install the toolchain via the official toolchain manager script
          wget https://nordicsemi.github.io/pc-nrfconnect-toolchain-manager/ToolchainManagerLinux.tar.gz
          tar -xzf ToolchainManagerLinux.tar.gz
          ./toolchain-manager --version
          
          # Use Toolchain Manager to install the correct version of the toolchain
          ./toolchain-manager install 2.6.1
          source ~/ncs/toolchain/v2.6.1/zephyr/zephyr-env.sh
          
      - name: Set up Zephyr environment (West and others)
        run: |
          pip3 install west
          west init -l nrfconnect-sdk
          west update
          west zephyr-export
          
      - name: Build the application for nRF52840
        run: |
          west build -b nrf52840dk_nrf52840

